<?php

/*
 * @package     XT Perfect SEO Pagination
 *
 * @author      Extly, CB. <team@extly.com>
 * @copyright   Copyright (c)2012-2025 Extly, CB. All rights reserved.
 * @license     https://www.gnu.org/licenses/gpl-3.0.html GNU/GPL
 *
 * @see         https://www.extly.com
 */

namespace Joomla\CMS\Pagination;

\defined('JPATH_PLATFORM') || exit;

use Joomla\CMS\Application\CMSApplication;

/**
 * Pagination Class. Provides a common interface for content pagination for the Joomla! CMS.
 *
 * @since  1.5
 */
class Pagination
{
    /**
     * @var int the record number to start displaying from
     *
     * @since  1.5
     */
    public $limitstart;

    /**
     * @var int number of rows to display per page
     *
     * @since  1.5
     */
    public $limit;

    /**
     * @var int total number of rows
     *
     * @since  1.5
     */
    public $total;

    /**
     * @var int prefix used for request variables
     *
     * @since  1.6
     */
    public $prefix;

    /**
     * @var int Value pagination object begins at
     *
     * @since  3.0
     */
    public $pagesStart;

    /**
     * @var int Value pagination object ends at
     *
     * @since  3.0
     */
    public $pagesStop;

    /**
     * @var int Current page
     *
     * @since  3.0
     */
    public $pagesCurrent;

    /**
     * @var int Total number of pages
     *
     * @since  3.0
     */
    public $pagesTotal;

    /**
     * @var bool The flag indicates whether to add limitstart=0 to URL
     *
     * @since  3.9.0
     */
    public $hideEmptyLimitstart = false;

    /**
     * @var bool View all flag
     *
     * @since  3.0
     */
    protected $viewall = false;

    /**
     * Additional URL parameters to be added to the pagination URLs generated by the class.  These
     * may be useful for filters and extra values when dealing with lists and GET requests.
     *
     * @var array
     *
     * @since  3.0
     */
    protected $additionalUrlParams = [];

    /**
     * @var CMSApplication The application object
     *
     * @since  3.4
     */
    protected $app;

    /**
     * Pagination data object
     *
     * @var object
     *
     * @since  3.4
     */
    protected $data;

    /**
     * Constructor.
     *
     * @param int            $total          the total number of items
     * @param int            $limitstart     the offset of the item to start at
     * @param int            $limit          the number of items to display per page
     * @param string         $prefix         the prefix used for request variables
     * @param CMSApplication $cmsApplication The application object
     *
     * @since   1.5
     */
    public function __construct($total, $limitstart, $limit, $prefix = '', CMSApplication $cmsApplication = null)
    {
        // Value/type checking.
        $this->total = (int) $total;
        $this->limitstart = (int) max($limitstart, 0);
        $this->limit = (int) max($limit, 0);
        $this->prefix = $prefix;
        $this->app = $cmsApplication ?: \JFactory::getApplication();

        if ($this->limit > $this->total) {
            $this->limitstart = 0;
        }

        if (0 === $this->limit) {
            $this->limit = $total;
            $this->limitstart = 0;
        }

        /*
         * If limitstart is greater than total (i.e. we are asked to display records that don't exist)
         * then set limitstart to display the last natural page of results
         */
        if ($this->limitstart > $this->total - $this->limit) {
            $this->limitstart = max(0, (int) (ceil($this->total / $this->limit) - 1) * $this->limit);
        }

        // Set the total pages and current page values.
        if ($this->limit > 0) {
            $this->pagesTotal = (int) ceil($this->total / $this->limit);
            $this->pagesCurrent = (int) ceil(($this->limitstart + 1) / $this->limit);
        }

        // Set the pagination iteration loop values.
        $displayedPages = 10;
        $this->pagesStart = $this->pagesCurrent - ($displayedPages / 2);

        if ($this->pagesStart < 1) {
            $this->pagesStart = 1;
        }

        if ($this->pagesStart + $displayedPages > $this->pagesTotal) {
            $this->pagesStop = $this->pagesTotal;
            $this->pagesStart = $this->pagesTotal < $displayedPages ? 1 : $this->pagesTotal - $displayedPages + 1;
        } else {
            $this->pagesStop = $this->pagesStart + $displayedPages - 1;
        }

        // If we are viewing all records set the view all flag to true.
        if (0 === $limit) {
            $this->viewall = true;
        }
    }

    /**
     * Method to set an additional URL parameter to be added to all pagination class generated
     * links.
     *
     * @param string $key   the name of the URL parameter for which to set a value
     * @param mixed  $value the value to set for the URL parameter
     *
     * @return mixed the old value for the parameter
     *
     * @since   1.6
     */
    public function setAdditionalUrlParam($key, $value)
    {
        // Get the old value to return and set the new one for the URL parameter.
        $result = $this->additionalUrlParams[$key] ?? null;

        // If the passed parameter value is null unset the parameter, otherwise set it to the given value.
        if (null === $value) {
            unset($this->additionalUrlParams[$key]);
        } else {
            $this->additionalUrlParams[$key] = $value;
        }

        return $result;
    }

    /**
     * Method to get an additional URL parameter (if it exists) to be added to
     * all pagination class generated links.
     *
     * @param string $key the name of the URL parameter for which to get the value
     *
     * @return mixed the value if it exists or null if it does not
     *
     * @since   1.6
     */
    public function getAdditionalUrlParam($key)
    {
        $result = $this->additionalUrlParams[$key] ?? null;

        return $result;
    }

    /**
     * Return the rationalised offset for a row with a given index.
     *
     * @param int $index The row index
     *
     * @return int rationalised offset for a row with a given index
     *
     * @since   1.5
     */
    public function getRowOffset($index)
    {
        return $index + 1 + $this->limitstart;
    }

    /**
     * Return the pagination data object, only creating it if it doesn't already exist.
     *
     * @return \stdClass pagination data object
     *
     * @since   1.5
     */
    public function getData()
    {
        if (!$this->data) {
            $this->data = $this->_buildDataObject();
        }

        return $this->data;
    }

    /**
     * Create and return the pagination pages counter string, ie. Page 2 of 4.
     *
     * @return string pagination pages counter string
     *
     * @since   1.5
     */
    public function getPagesCounter()
    {
        $html = null;

        if ($this->pagesTotal > 1) {
            $html .= \JText::sprintf('JLIB_HTML_PAGE_CURRENT_OF_TOTAL', $this->pagesCurrent, $this->pagesTotal);
        }

        return $html;
    }

    /**
     * Create and return the pagination result set counter string, e.g. Results 1-10 of 42
     *
     * @return string pagination result set counter string
     *
     * @since   1.5
     */
    public function getResultsCounter()
    {
        $html = null;
        $fromResult = $this->limitstart + 1;

        // If the limit is reached before the end of the list.
        $toResult = $this->limitstart + $this->limit < $this->total ? $this->limitstart + $this->limit : $this->total;

        // If there are results found.
        if ($this->total > 0) {
            $msg = \JText::sprintf('JLIB_HTML_RESULTS_OF', $fromResult, $toResult, $this->total);
            $html .= "\n".$msg;
        } else {
            $html .= "\n".\JText::_('JLIB_HTML_NO_RECORDS_FOUND');
        }

        return $html;
    }

    /**
     * Create and return the pagination page list string, ie. Previous, Next, 1 2 3 ... x.
     *
     * @return string pagination page list string
     *
     * @since   1.5
     */
    public function getPagesLinks()
    {
        // Build the page navigation list.
        $data = $this->_buildDataObject();

        $list = [];
        $list['prefix'] = $this->prefix;

        $itemOverride = false;
        $listOverride = false;

        $chromePath = JPATH_THEMES.'/'.$this->app->getTemplate().'/html/pagination.php';

        if (file_exists($chromePath)) {
            include_once $chromePath;

            /*
             * @deprecated 4.0 Item rendering should use a layout
             */
            if (\function_exists('pagination_item_active') && \function_exists('pagination_item_inactive')) {
                \JLog::add(
                    'pagination_item_active and pagination_item_inactive are deprecated. Use the layout joomla.pagination.link instead.',
                    \JLog::WARNING,
                    'deprecated'
                );

                $itemOverride = true;
            }

            /*
             * @deprecated 4.0 The list rendering is now a layout.
             * @see Pagination::_list_render()
             */
            if (\function_exists('pagination_list_render')) {
                \JLog::add('pagination_list_render is deprecated. Use the layout joomla.pagination.list instead.', \JLog::WARNING, 'deprecated');
                $listOverride = true;
            }
        }

        // Build the select list
        if (null !== $data->all->base) {
            $list['all']['active'] = true;
            $list['all']['data'] = $itemOverride ? pagination_item_active($data->all) : $this->_item_active($data->all);
        } else {
            $list['all']['active'] = false;
            $list['all']['data'] = $itemOverride ? pagination_item_inactive($data->all) : $this->_item_inactive($data->all);
        }

        if (null !== $data->start->base) {
            $list['start']['active'] = true;
            $list['start']['data'] = $itemOverride ? pagination_item_active($data->start) : $this->_item_active($data->start);
        } else {
            $list['start']['active'] = false;
            $list['start']['data'] = $itemOverride ? pagination_item_inactive($data->start) : $this->_item_inactive($data->start);
        }

        if (null !== $data->previous->base) {
            $list['previous']['active'] = true;
            $list['previous']['data'] = $itemOverride ? pagination_item_active($data->previous) : $this->_item_active($data->previous);
        } else {
            $list['previous']['active'] = false;
            $list['previous']['data'] = $itemOverride ? pagination_item_inactive($data->previous) : $this->_item_inactive($data->previous);
        }

        // Make sure it exists
        $list['pages'] = [];

        foreach ($data->pages as $i => $page) {
            if (null !== $page->base) {
                $list['pages'][$i]['active'] = true;
                $list['pages'][$i]['data'] = $itemOverride ? pagination_item_active($page) : $this->_item_active($page);
            } else {
                $list['pages'][$i]['active'] = false;
                $list['pages'][$i]['data'] = $itemOverride ? pagination_item_inactive($page) : $this->_item_inactive($page);
            }
        }

        if (null !== $data->next->base) {
            $list['next']['active'] = true;
            $list['next']['data'] = $itemOverride ? pagination_item_active($data->next) : $this->_item_active($data->next);
        } else {
            $list['next']['active'] = false;
            $list['next']['data'] = $itemOverride ? pagination_item_inactive($data->next) : $this->_item_inactive($data->next);
        }

        if (null !== $data->end->base) {
            $list['end']['active'] = true;
            $list['end']['data'] = $itemOverride ? pagination_item_active($data->end) : $this->_item_active($data->end);
        } else {
            $list['end']['active'] = false;
            $list['end']['data'] = $itemOverride ? pagination_item_inactive($data->end) : $this->_item_inactive($data->end);
        }

        if ($this->total > $this->limit) {
            return $listOverride ? pagination_list_render($list) : $this->_list_render($list);
        }

        return '';
    }

    /**
     * Get the pagination links
     *
     * @param string $layoutId Layout to render the links
     * @param array  $options  Optional array with settings for the layout
     *
     * @return string pagination links
     *
     * @since   3.3
     */
    public function getPaginationLinks($layoutId = 'joomla.pagination.links', $options = [])
    {
        // Allow to receive a null layout
        $layoutId ??= 'joomla.pagination.links';

        $list = [
            'prefix'       => $this->prefix,
            'limit'        => $this->limit,
            'limitstart'   => $this->limitstart,
            'total'        => $this->total,
            'limitfield'   => $this->getLimitBox(),
            'pagescounter' => $this->getPagesCounter(),
            'pages'        => $this->getPaginationPages(),
            'pagesTotal'   => $this->pagesTotal,
        ];

        return \JLayoutHelper::render($layoutId, ['list' => $list, 'options' => $options]);
    }

    /**
     * Create and return the pagination pages list, ie. Previous, Next, 1 2 3 ... x.
     *
     * @return array pagination pages list
     *
     * @since   3.3
     */
    public function getPaginationPages()
    {
        $list = [];

        if ($this->total > $this->limit) {
            // Build the page navigation list.
            $data = $this->_buildDataObject();

            // All
            $list['all']['active'] = null !== $data->all->base;
            $list['all']['data'] = $data->all;

            // Start
            $list['start']['active'] = null !== $data->start->base;
            $list['start']['data'] = $data->start;

            // Previous link
            $list['previous']['active'] = null !== $data->previous->base;
            $list['previous']['data'] = $data->previous;

            // Make sure it exists
            $list['pages'] = [];

            foreach ($data->pages as $i => $page) {
                $list['pages'][$i]['active'] = null !== $page->base;
                $list['pages'][$i]['data'] = $page;
            }

            $list['next']['active'] = null !== $data->next->base;
            $list['next']['data'] = $data->next;

            $list['end']['active'] = null !== $data->end->base;
            $list['end']['data'] = $data->end;
        }

        return $list;
    }

    /**
     * Return the pagination footer.
     *
     * @return string pagination footer
     *
     * @since   1.5
     */
    public function getListFooter()
    {
        // Keep B/C for overrides done with chromes
        $chromePath = JPATH_THEMES.'/'.$this->app->getTemplate().'/html/pagination.php';

        if (file_exists($chromePath)) {
            include_once $chromePath;

            if (\function_exists('pagination_list_footer')) {
                \JLog::add('pagination_list_footer is deprecated. Use the layout joomla.pagination.links instead.', \JLog::WARNING, 'deprecated');

                $list = [
                    'prefix'       => $this->prefix,
                    'limit'        => $this->limit,
                    'limitstart'   => $this->limitstart,
                    'total'        => $this->total,
                    'limitfield'   => $this->getLimitBox(),
                    'pagescounter' => $this->getPagesCounter(),
                    'pageslinks'   => $this->getPagesLinks(),
                ];

                return pagination_list_footer($list);
            }
        }

        return $this->getPaginationLinks();
    }

    /**
     * Creates a dropdown box for selecting how many records to show per page.
     *
     * @return string the HTML for the limit # input box
     *
     * @since   1.5
     */
    public function getLimitBox()
    {
        $limits = [];

        // Make the option list.
        for ($i = 5; $i <= 30; $i += 5) {
            $limits[] = \JHtml::_('select.option', $i);
        }

        $limits[] = \JHtml::_('select.option', '50', \JText::_('J50'));
        $limits[] = \JHtml::_('select.option', '100', \JText::_('J100'));
        $limits[] = \JHtml::_('select.option', '0', \JText::_('JALL'));

        $selected = $this->viewall ? 0 : $this->limit;

        // Build the select list.
        if ($this->app->isClient('administrator')) {
            return \JHtml::_(
                'select.genericlist',
                $limits,
                $this->prefix.'limit',
                'class="inputbox input-mini" size="1" onchange="Joomla.submitform();"',
                'value',
                'text',
                $selected
            );
        }

        return \JHtml::_(
            'select.genericlist',
            $limits,
            $this->prefix.'limit',
            'class="inputbox input-mini" size="1" onchange="this.form.submit()"',
            'value',
            'text',
            $selected
        );
    }

    /**
     * Return the icon to move an item UP.
     *
     * @param int    $i         the row index
     * @param bool   $condition true to show the icon
     * @param string $task      the task to fire
     * @param string $alt       the image alternative text string
     * @param bool   $enabled   an optional setting for access control on the action
     * @param string $checkbox  an optional prefix for checkboxes
     *
     * @return string either the icon to move an item up or a space
     *
     * @since   1.5
     */
    public function orderUpIcon($i, $condition = true, $task = 'orderup', $alt = 'JLIB_HTML_MOVE_UP', $enabled = true, $checkbox = 'cb')
    {
        if (($i > 0 || ($i + $this->limitstart > 0)) && $condition) {
            return \JHtml::_('jgrid.orderUp', $i, $task, '', $alt, $enabled, $checkbox);
        }

        return '&#160;';
    }

    /**
     * Return the icon to move an item DOWN.
     *
     * @param int    $i         the row index
     * @param int    $n         the number of items in the list
     * @param bool   $condition true to show the icon
     * @param string $task      the task to fire
     * @param string $alt       the image alternative text string
     * @param bool   $enabled   an optional setting for access control on the action
     * @param string $checkbox  an optional prefix for checkboxes
     *
     * @return string either the icon to move an item down or a space
     *
     * @since   1.5
     */
    public function orderDownIcon($i, $n, $condition = true, $task = 'orderdown', $alt = 'JLIB_HTML_MOVE_DOWN', $enabled = true, $checkbox = 'cb')
    {
        if (($i < $n - 1 || $i + $this->limitstart < $this->total - 1) && $condition) {
            return \JHtml::_('jgrid.orderDown', $i, $task, '', $alt, $enabled, $checkbox);
        }

        return '&#160;';
    }

    /**
     * Modifies a property of the object, creating it if it does not already exist.
     *
     * @param string $property the name of the property
     * @param mixed  $value    the value of the property to set
     *
     * @return void
     *
     * @since   3.0
     * @deprecated  4.0  Access the properties directly.
     */
    public function set($property, $value = null)
    {
        \JLog::add('Pagination::set() is deprecated. Access the properties directly.', \JLog::WARNING, 'deprecated');

        if (strpos($property, '.')) {
            $prop = explode('.', $property);
            $prop[1] = ucfirst($prop[1]);
            $property = implode('', $prop);
        }

        $this->$property = $value;
    }

    /**
     * Returns a property of the object or the default value if the property is not set.
     *
     * @param string $property the name of the property
     * @param mixed  $default  the default value
     *
     * @return mixed the value of the property
     *
     * @since   3.0
     * @deprecated  4.0  Access the properties directly.
     */
    public function get($property, $default = null)
    {
        \JLog::add('Pagination::get() is deprecated. Access the properties directly.', \JLog::WARNING, 'deprecated');

        if (strpos($property, '.')) {
            $prop = explode('.', $property);
            $prop[1] = ucfirst($prop[1]);
            $property = implode('', $prop);
        }

        return $this->$property ?? $default;
    }

    /**
     * Create the HTML for a list footer
     *
     * @param array $list pagination list data structure
     *
     * @return string HTML for a list footer
     *
     * @since   1.5
     */
    protected function _list_footer($list)
    {
        $html = "<div class=\"list-footer\">\n";

        $html .= "\n<div class=\"limit\">".\JText::_('JGLOBAL_DISPLAY_NUM').$list['limitfield'].'</div>';
        $html .= $list['pageslinks'];
        $html .= "\n<div class=\"counter\">".$list['pagescounter'].'</div>';

        $html .= "\n<input type=\"hidden\" name=\"".$list['prefix'].'limitstart" value="'.$list['limitstart'].'" />';
        $html .= "\n</div>";

        return $html;
    }

    /**
     * Create the html for a list footer
     *
     * @param array $list pagination list data structure
     *
     * @return string HTML for a list start, previous, next,end
     *
     * @since   1.5
     */
    protected function _list_render($list)
    {
        return \JLayoutHelper::render('joomla.pagination.list', ['list' => $list]);
    }

    /**
     * Method to create an active pagination link to the item
     *
     * @param PaginationObject $paginationObject the object with which to make an active link
     *
     * @return string HTML link
     *
     * @since   1.5
     *
     * @note    As of 4.0 this method will proxy to `\JLayoutHelper::render('joomla.pagination.link', ['data' => $item, 'active' => true])`
     */
    protected function _item_active(PaginationObject $paginationObject)
    {
        $title = '';
        $class = '';

        if (!is_numeric($paginationObject->text)) {
            \JHtml::_('bootstrap.tooltip');
            $title = ' title="'.$paginationObject->text.'"';
            $class = 'hasTooltip ';
        }

        if ($this->app->isClient('administrator')) {
            return '<a'.$title.' href="#" onclick="document.adminForm.'.$this->prefix
            .'limitstart.value='.($paginationObject->base > 0 ? $paginationObject->base : '0').'; Joomla.submitform();return false;">'.$paginationObject->text.'</a>';
        }

        return '<a'.$title.' href="'.$paginationObject->link.'" class="'.$class.'pagenav">'.$paginationObject->text.'</a>';
    }

    /**
     * Method to create an inactive pagination string
     *
     * @param PaginationObject $paginationObject The item to be processed
     *
     * @return string
     *
     * @since   1.5
     *
     * @note    As of 4.0 this method will proxy to `\JLayoutHelper::render('joomla.pagination.link', ['data' => $item, 'active' => false])`
     */
    protected function _item_inactive(PaginationObject $paginationObject)
    {
        if ($this->app->isClient('administrator')) {
            return '<span>'.$paginationObject->text.'</span>';
        }

        return '<span class="pagenav">'.$paginationObject->text.'</span>';
    }

    /**
     * Create and return the pagination data object.
     *
     * @return \stdClass pagination data object
     *
     * @since   1.5
     */
    protected function _buildDataObject()
    {
        $data = new \stdClass();

        // Build the additional URL parameters string.
        $params = '';

        if (!empty($this->additionalUrlParams)) {
            foreach ($this->additionalUrlParams as $key => $value) {
                $params .= '&'.$key.'='.$value;
            }
        }

        $data->all = new PaginationObject(\JText::_('JLIB_HTML_VIEW_ALL'), $this->prefix);

        if (!$this->viewall) {
            $data->all->base = '0';
            $data->all->link = \JRoute::_($params.'&'.$this->prefix.'limitstart=');
        }

        // Set the start and previous data objects.
        $data->start = new PaginationObject(\JText::_('JLIB_HTML_START'), $this->prefix);
        $data->previous = new PaginationObject(\JText::_('JPREV'), $this->prefix);

        if ($this->pagesCurrent > 1) {
            $page = ($this->pagesCurrent - 2) * $this->limit;

            if ($this->hideEmptyLimitstart) {
                $data->start->link = \JRoute::_($params.'&'.$this->prefix.'limitstart=');
            } else {
                $data->start->link = \JRoute::_($params.'&'.$this->prefix.'limitstart=0');
            }

            $data->start->base = '0';
            $data->previous->base = $page;

            if (0 === $page && $this->hideEmptyLimitstart) {
                $data->previous->link = $data->start->link;
            } else {
                $data->previous->link = \JRoute::_($params.'&'.$this->prefix.'limitstart='.$page);
            }
        }

        // Set the next and end data objects.
        $data->next = new PaginationObject(\JText::_('JNEXT'), $this->prefix);
        $data->end = new PaginationObject(\JText::_('JLIB_HTML_END'), $this->prefix);

        if ($this->pagesCurrent < $this->pagesTotal) {
            $next = $this->pagesCurrent * $this->limit;
            $end = ($this->pagesTotal - 1) * $this->limit;

            $data->next->base = $next;
            $data->next->link = \JRoute::_($params.'&'.$this->prefix.'limitstart='.$next);
            $data->end->base = $end;
            $data->end->link = \JRoute::_($params.'&'.$this->prefix.'limitstart='.$end);
        }

        $data->pages = [];
        $stop = $this->pagesStop;

        for ($i = $this->pagesStart; $i <= $stop; $i++) {
            $offset = ($i - 1) * $this->limit;

            $data->pages[$i] = new PaginationObject($i, $this->prefix);

            if ($i != $this->pagesCurrent || $this->viewall) {
                $data->pages[$i]->base = $offset;

                if (0 === $offset && $this->hideEmptyLimitstart) {
                    $data->pages[$i]->link = $data->start->link;
                } else {
                    $data->pages[$i]->link = \JRoute::_($params.'&'.$this->prefix.'limitstart='.$offset);
                }
            } else {
                $data->pages[$i]->active = true;
            }
        }

        \Extly\Pagination\XTPaginationHelper::generateSeoLinkRelPagination($data);

        return $data;
    }
}
